### ISSUE TITLE
ID15 buble-chartの不具合

### ISSUE THREAD

**Issue by y-sama** [e2d3/e2d3-contrib#162]
1. 表頭データを変更すると描画しなくなる。
2. 行を挿入した時に挿入したデータが反映されない。

  - テスト項目にはなかったが、sunshine_durationとwind_speedは値を変更しても反映されない（temperatureのみ反映される）
  - ブックを開きなおすと反映される

3. ~~pngで出力した時に、背景色がおかしい（サムネイルは白、開くと黒）~~
chromebookの画像ビューア特有の不具合でした。jupyter notebook上で表示させると問題なし。

以下、テスト項目外での不具合。
4. X軸の横線と軸名（sunshine_duration）が表示されていない。

**Comment by keisuke-osone** [comment]
#164 
にて動作確認されたのでクローズします。
