### ISSUE TITLE
Not be drawn on Yamaguchi Map（Yamaguchi Mapが表示されない）

### ISSUE THREAD

**Issue by JunichiWatanuki** [e2d3/e2d3-contrib#180]
:uk:
Not be drawn on Yamaguchi Map
:jp:
Yamaguchi Mapが表示されない

:uk:
Now writing!!
:jp:
下記の環境にて動作試験に合格した後にマージを行ったが、本番環境では画面表示が行われない。
■■■動作確認できた環境
　試験環境１）　Win10 × Excel2016（Delegate Mode）
　試験環境２）　Win10 × Chrome（Delegate Mode）
　試験環境３）　Win10 × Edge（Delegate Mode）
　試験環境４）　Win10 × Internet Exploler（Delegate Mode）
■■■画面表示出来なかった環境
　試験環境５）　Win10 × Excel2016
　試験環境６）　Win10 × Chrome
　試験環境７）　Win10 × Edge
　試験環境８）　Win10 × Internet Exploler

Delegate Modeでは動作できて、本番環境では描画ができない事象に関しまして、過去事例などの情報をお持ちの方がいらっしゃいましたら、水平展開をしていただけますと助かります。
@fdfpy さんの環境でも同様であるか、お時間のある時に情報をお寄せいただけましたら助かります。

**Comment by hipsrinoky** [comment]
原因はファイル容量が大きすぎるためです。Githubのapi制限に引っかかっています。

delegate modeでは、ローカルのファイルを見ていますが、
本番環境では、Github -> e2d3 cacheサーバの段階で、引っ張れていないはずです。
また、恐らくGithubへのxhrアクセスでも無理だと思います。
厳密なLimitはドキュメントが見つかりませんでした...。

経験則としては、1MBを超えると怪しいです。

対応策としては、topojsonに含まれるデータの軽減（丁番などが必要ない場合は削るなど）、もしくはminify処理などをすれば大丈夫のはずです。

**Comment by hipsrinoky** [comment]
https://developer.github.com/v3/repos/contents/#get-contents
wikiの方にも載せないとだめですね。

> Note:
get a repository's contents recursively, you can recursively get the tree.
This API has an upper limit of 1,000 files for a directory. If you need to retrieve more files, use the Git Trees API.
This API supports files up to 1 megabyte in size.

**Comment by hipsrinoky** [comment]
@JunichiWatanuki Wiki pages ware updated. and Can I close this comment?

https://github.com/e2d3/e2d3/wiki/Structure-of-data-visualization-template_ja
https://github.com/e2d3/e2d3/wiki/Structure-of-data-visualization-template

**Comment by fdfpy** [comment]
対策案どうもありがとうございます。どうやって解析しようか迷っていたところです。
topojsonファイルのデータ量の削減にトライしてみます。

**Comment by hipsrinoky** [comment]
宜しくお願い申し上げます。ということで、このissueは閉じますね♫
