### ISSUE TITLE
License of using e2d3-contrib?

### ISSUE THREAD

**Issue by chfw** [e2d3/e2d3-contrib#197]
Hi all,

What kind of license e2d3-contrib is under? Apache 2.0?

Cheers

jaska

**Comment by yasunobuigarashi** [comment]
Dear jaska

Thank you for your question!
Yes, the license of e2d3/e2d3-contrib is under Apache 2.0 as well as e2d3/e2d3.

I added the license file as below
https://github.com/e2d3/e2d3-contrib/blob/master/LICENSE

We appreciate your contribution!

Sincerely yours, 
Yasunobu Igarashi 
a founder and PJ leader of E2D3

**Comment by chfw** [comment]
Appreciated it. Cheers.
