### ISSUE TITLE
バグレポート

### ISSUE THREAD

**Issue by yasunobuigarashi** [e2d3/e2d3-contrib#208]
ishikawa mapは動かすと、データとグラフのリンクが切れて、図の中が白くなる、データが表示されなくなるというレポートをうけました。ご確認お願いします。

**Comment by fdfpy** [comment]
EXCEL2016 , Office onlineで調べてみましたが、私の環境では正常に動作しました。
ただ、EXCEL onlineの場合は、wifiの通信速度が追い付いていないためしばらくデータが表示されないことがありました。
また同じ現象が再発したときはご連絡ください。対応させていただきます。
