### ISSUE TITLE
【バグ】データより右側の文字群が少なく表示される-Word Cloud

### ISSUE THREAD

**Issue by natsukisato** [e2d3/e2d3-contrib#209]
CodeZineの記事を書いていた際発見しました（共有遅くなりすみません）。
近日中に記事がアップされると思うので、どなたか対応いただけますと幸いでございます。

--
・対象：テンプレート「Word Cloud」
・事象：データよりも右側の文字群が少なく表示される
10件なら8〜9件表示といった具合です。
「データ範囲を再設定する」をクリックし読み込んだり、数字を変えたりすると、先ほど読み込まれなかったデータとは異なるデータが抜けたりします。
比較的数の多いものがなくなる傾向にあります。

確認のほどよろしくお願いします。

**Comment by fdfpy** [comment]
私の環境（EXCEL2016 and EXCEL ONLINE)で確認しましたが、ご指摘された不具合は再現されませんでした。
![default](https://cloud.githubusercontent.com/assets/15305650/18223147/0631bd2c-71e9-11e6-88d1-9a2cd810a4f8.png)
