### ISSUE TITLE
【要望】X軸を西暦にしたい：dot-bar-chart

### ISSUE THREAD

**Issue by natsukisato** [e2d3/e2d3-contrib#210]
すみません、こちらもCodeZineの記事を書いていた際気になったことです。

--
・要望：dot-bar-chartのX軸を「0〜5」→「2010〜2015」にしたい

単位がデフォルトで「year」となっているので、それに合わせたほうがいいのでは？と思いまして。

ご検討いただけると幸いでございます。

**Comment by y-minoda** [comment]
西暦に変更しました。

**Comment by natsukisato** [comment]
確認しました。対応ありがとうございました。
