### ISSUE TITLE
Bug 川上くんの徒競走：川上くん非表示　foot-race lost its athletes

### ISSUE THREAD

**Issue by yupa884** [e2d3/e2d3-contrib#211]
不具合概要
徒競走の走者のイメージ（青い人間の絵）が表示されない。
foot-race lost its athletes
正常：トラック上を走者がそのタイトルと一緒に駆け抜ける。
現状：走者のタイトル（白いテキスト）だけが右側へ移動していく。

事象発生環境 environment version
Mac & Online
Google chrome Version 50.0.2661.102 (64-bit)

発生した時の操作
One Drive上で当該グラフを選択して、自動的に起動した際の最初の画面。

発生確率 recall
必ず再現する 100%

エラーメッセージなど message
jQuery is not a function

PCの環境によるようで、小副川さんのPC（windows & Excel）では起動することを7月2日に確認しましたが、OneDriveでは表示されない状態が続いています。

ラベルのつけ方がわかりませんが、これはBugです。

**Comment by yasunobuigarashi** [comment]
@fdfpy さんが直してくれたのでclosedします、感謝！
https://github.com/e2d3/e2d3-contrib/pull/214

**Comment by yasunobuigarashi** [comment]
WinとMacのExcel2016
1 エラーメッセージ：jQuery is not a functionが表示されっぱなし→表示されなくなった
2 グラフ：トラック上を走者がそのタイトルと一緒に駆け抜ける。→そのまま正しく表示

Onedrive（Excel Online）
3 エラーメッセージ：jQuery is not a functionが表示されっぱなし→表示されなくなった
4 グラフ：現状：走者のタイトル（白いテキスト）だけが右側へ移動していく。→そのまま誤って表示

上記の問題４が問題のまま残っていたので、Reopenしました。
引き続き、改善してくださる方を募集しております！

**Comment by kxhjp09** [comment]
ExcelOnlineで表示されるように修正しました。Mac/WinのExcel2016でのテストをどなたかお願いできますか？

**Comment by hajime-miyauchi** [comment]
Mac/WinのExcel2016で動作確認しました！Closeします。
