### ISSUE TITLE
画像（aicon,背景）カスタマイズフリーなテンプレートがあったら！

### ISSUE THREAD

**Issue by kiryu001** [e2d3/e2d3-contrib#262]
RecommendedのForce Graphは、すごくできることが多そうなので、ガンガン使いたいです！
http://a.e2d3.org/chart.html#force-graph!js!csv

この画像には丸と線が存在します。
この丸と線ををExcel上から差し替えられるようにして欲しいです。

丸（●）  → 画像差し替え
線 → 太さ変更、長さ変更
色→カラーコード or RGB入力

子供達やコード書けない人も、自由にカスタマイズできたら！
ステキな未来予想図妄想しています！
このグラフがカスタマイズフリーになったら、他のグラフも優先順位をつけてまたお願いしたいです

**Comment by JunichiWatanuki** [comment]
@kiryu001　ご提案ありがとうございます。
参考にして、E2D3のテンプレ作成してみたいと思います。

**Comment by kiryu001** [comment]
ご快諾ありがとうございます😊
ステキな広がり 可視化できるようイメトレいたします！

**Comment by JunichiWatanuki** [comment]
@kiryu001 さん。
とりあえず、色などをカスタマイズできるイメージを下記のように作りました。
http://a.e2d3.org/chart.html#force-directed-graph!js!tsv

**Comment by JunichiWatanuki** [comment]
このイメージで進めてよろしければ、デバッグ作業（一部動作しない）を修正したいと思います。

**Comment by kiryu001** [comment]
@JunichiWatanuki さん
ありがとうございます！
スゴイカラフルになっていますね！また詳しくご教授くださいませ！
お忙しい中、ありがとうございました！

**Comment by JunichiWatanuki** [comment]
@kiryu001 さま。
Excel2016で、データ更新に連動すべき再描画不具合を直しました。
このテンプレでよろしければ、このIssueのCloseをしたいと思います。
（ご連絡をお待ちしております）

**Comment by kiryu001** [comment]
ありがとうございます😊
何卒よろしくお願いいたします。
