### ISSUE TITLE
画像の保存先

### ISSUE THREAD

**Issue by maruosueo** [e2d3/e2d3-contrib#280]
初めまして。
E2D3をhigh sierra上のexcel2016で使用しています。
そこで質問ですが、「画像を保存」にした場合の保存先はどこになるのでしょうか？
１時間ほど検索したのですが、有益な情報に行き当たりませんでした。

よろしくお願い致します。

**Comment by yasunobuigarashi** [comment]
保存先は、通常のダウンロードファイルになります！
