### ISSUE TITLE
History mapの写真が表示されないケースがあるかもしれない

### ISSUE THREAD

**Issue by takuya310** [e2d3/e2d3-contrib#301]
History mapを作成するため、写真のURLセルに共有URLを入力しましたが、以下のURLを入力した場合は表示されませんでした。サンプルデータの通りに、Wikimediaに写真を登録した場合は、表示されました。

・Google Driveの共有用URL（リンクを知っている人は誰でも閲覧可能）
・Flickrの共有URL

これらには拡張子が付いていないので、そこが影響しているかもしれないと思いました。
（Wikimediaは付いている）

前はGoogle DriveのURLで行けていたとのことだったので、issueにあげておきます。

**Comment by hipsrinoky** [comment]
こんにちは。Issue登録有難うございます。
拡張子が付いていないURLについては、恐らく、画像データへのURLではなく、画像を閲覧するためのページURLになるかと思います。

画像データへの直リンク（URL）がお分かりになりましたら、そちらでお試しくださいませ。
（
Google Drive等では、通常は直リンクURLは発行していないようですが、共有用URLのパラメータを部分的に変更することで、直接画像ファイルにアクセスするURLに変更できるみたいです。
参考： https://qiita.com/tworks55/items/a1231652b88fd5855b9b
）

**Comment by takuya310** [comment]
レスに気づくのが大変遅くなりすみません。
ありがとうございました。直接URLで対応いたします。
