### ISSUE TITLE
DLした画像でもマウスオーバーが効く　【要望度B】

### ISSUE THREAD

**Issue by takeshino** [e2d3/e2d3-contrib#39]
pptに貼って使うことが多いので。
そのときにどこがどの県で、、、この色は何％で、、、とか説明しなくて済むとラク。

　＊もしくは、地図上にラベル/値を表示させる機能。

**Comment by nakamods320yen** [comment]
これはjsやhtmlファイルを丸ごとダウンロードすればいけそうですね。画像単体だと厳しいです

**Comment by nakamods320yen** [comment]
県名や値と色の凡例を出すのは簡単だと思います

**Comment by hipsrinoky** [comment]
これ、恐らくE2D3 on PPTができて、そんでもってユーザーアカウントが実装されれば、PPTの中でもリアルタイムに動くと思いますねぇ。それはとっても有用だと僕も思います。

**Comment by JunichiWatanuki** [comment]
かわまいさんが情報をまとめてくださっています。
http://tekumemo.blog.jp/archives/10242578.html
