### ISSUE TITLE
Map Projection Distortionsのバグ

### ISSUE THREAD

**Issue by ShinSOEJIMA** [e2d3/e2d3-contrib#48]
これは、とある報道機関が作成しているホームページで、
ニュースを分野別に分類したときに、どの分野のニュースに
どれだけ閲覧があったのか、まとめたデータです。

17日	18日	19日	20日	name
120	110	130	150	社会
30	50	15	20	科学・医療
10	100	30	45	政治
80	40	20	10	経済
30	130	150	160	国際
100	120	120	110	スポーツ
40	50	40	30	文化・エンタメ
20	40	40	10	その他

これでグラフを作ってみました。
どの分野の閲覧数が多いか、データを調べようと思ったのですが、
１７日の部分だけ思ったような結果が出ませんでした。

つまり、１８日から２０日はグラフの縦軸が昇順になったのですが、
１７日は降順になりました。

これはバグかもしれませんので、ご確認お願いいたします。

**Comment by JunichiWatanuki** [comment]
@ShinSOEJIMA さま。
Generalize map-projection-distortions #88により修正されておりますので、Closeとさせていただきます。

下記のように修正されておりますので、お時間のある時にご確認いただけしたら幸いです。
17日	120	30	10	80	30	100	40	20
18日	110	50	100	40	130	120	50	40
19日	130	15	30	20	150	120	40	40
20日	150	20	45	10	160	110	30	10
https://s.e2d3.org/4790eb3/44136fa/c39f04176dc953acf6084b7165c41564




name	17日	18日	19日	20日
社会	120	110	130	150
科学・医療	30	50	15	20
政治	10	100	30	45
経済	80	40	20	10
国際	30	130	150	160
スポーツ	100	120	120	110
文化・エンタメ	40	50	40	30
その他	20	40	40	10
https://s.e2d3.org/4790eb3/44136fa/b1d83af8e60d1ab3cc9df5d4d0dc5c2e
